runtime: nodejs14  # Use the latest supported Node.js version.

instance_class: F2


env_variables:
  NODE_ENV: 'production'

entrypoint: npm start

handlers:
- url: /favicon\.ico
  static_files: public/favicon.ico
  upload: public/favicon\.ico
  
- url: /static
  static_dir: build/static

- url: /.*
  static_files: build/index.html
  upload: build/index.html
